# Generated by Django 4.0.5 on 2022-07-22 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalName', models.CharField(max_length=30, unique=True)),
                ('ownerUsername', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('b_date', models.DateField(max_length=20)),
                ('gender', models.CharField(choices=[('m', 'm'), ('f', 'f')], max_length=30)),
                ('species', models.CharField(choices=[('domestic', 'domestic'), ('wild', 'wild')], max_length=30)),
                ('female_state', models.CharField(blank=True, choices=[('immature', 'immature'), ('mature&married', 'mature&married'), ('pregnant ', 'pregnant'), ('lactating', 'lactating')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('work_hours_start', models.IntegerField()),
                ('work_hours_start_period', models.CharField(choices=[('am', 'am'), ('pm', 'pm')], max_length=2)),
                ('work_hours_end', models.IntegerField()),
                ('work_hours_end_period', models.CharField(choices=[('am', 'am'), ('pm', 'pm')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('sender', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 7, 22, 11, 11, 22, 35038))),
            ],
        ),
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('b_date', models.DateField(max_length=20, null=True)),
                ('active_status', models.BooleanField(default=False)),
                ('face_link', models.URLField(null=True)),
                ('active_link', models.URLField(null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('b_date', models.DateField(blank=True, max_length=20, null=True)),
                ('active_status', models.BooleanField(default=False)),
                ('face_link', models.URLField(blank=True, null=True)),
                ('active_link', models.URLField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=40)),
                ('specialization', models.CharField(choices=[('poultry', 'poultry'), ('equine', 'equine'), ('ruminant', 'ruminant'), ('fishes and aquatics', 'fishes and aquatics'), ('obstetrics and gynecology', 'obstetrics and gynecology')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
