# Generated by Django 4.0.5 on 2022-07-24 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_messages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 3, 31, 1, 399389)),
        ),
        migrations.AlterField(
            model_name='vet',
            name='profile_pic',
            field=models.ImageField(upload_to='profileImages'),
        ),
    ]
