# Generated by Django 4.0.5 on 2022-07-24 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_messages_date_alter_vet_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 4, 14, 54, 867702)),
        ),
        migrations.AlterField(
            model_name='vet',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
