# Generated by Django 4.0.5 on 2022-07-24 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_messages_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 5, 38, 58, 471914)),
        ),
    ]
