# Generated by Django 4.0.5 on 2022-07-24 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_messages_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 5, 39, 51, 761930)),
        ),
    ]
