# Generated by Django 4.0.5 on 2022-07-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_messages_date_alter_vet_profile_pic'),
        ('api', '0009_locations_mobile_alter_messages_date'),
    ]

    operations = [
    ]
