# Generated by Django 4.0.5 on 2022-07-24 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20220724_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('cow', 'cow')], max_length=30),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 17, 13, 24, 435584)),
        ),
    ]
