# Generated by Django 4.0.5 on 2022-07-24 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_animal_picture_alter_animal_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='dateModified',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 18, 38, 47, 678865)),
        ),
    ]
