# Generated by Django 4.0.5 on 2022-07-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_messages_datemodified_alter_messages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(default='in method date of datetime.datetime object at 0x000002BFDFEA4AB0>/24', max_length=30),
        ),
    ]
