# Generated by Django 4.0.5 on 2022-07-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_messages_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='dateModified',
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(default='2022-07-24', max_length=30),
        ),
    ]
