# Generated by Django 4.0.5 on 2022-07-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_messages_datemodified_alter_messages_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='city',
            field=models.CharField(default='cairo', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(default='2022-07-25', max_length=30),
        ),
    ]
