# Generated by Django 4.0.5 on 2022-07-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_locations_city_alter_messages_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='city',
            new_name='governorate',
        ),
    ]
