# Generated by Django 4.0.5 on 2022-07-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_myuser_country_myuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
    ]
