# Generated by Django 4.0.5 on 2022-07-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_myuser_isonline_vet_isonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='b_date',
            field=models.DateField(default='2022-04-1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='face_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
