# Generated by Django 4.0.5 on 2022-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_myuser_address_alter_myuser_b_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='b_date',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
