# Generated by Django 4.0.5 on 2022-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_myuser_b_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='b_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='face_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
