# Generated by Django 4.0.5 on 2022-07-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_myuser_b_date_alter_myuser_face_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='face_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
