# Generated by Django 4.0.5 on 2022-07-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_vet_face_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalName', models.CharField(max_length=30)),
                ('vetName', models.CharField(max_length=30)),
                ('medicationName', models.CharField(max_length=30)),
                ('dosage', models.IntegerField()),
                ('dosageInterval', models.IntegerField()),
                ('adminstrationRoute', models.CharField(blank=True, choices=[('route1', 'route1'), ('route2', 'route2'), ('route3 ', 'route3')], max_length=30, null=True)),
                ('date', models.CharField(default='2022-07-25', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalName', models.CharField(max_length=30)),
                ('vetName', models.CharField(max_length=30)),
                ('operationName', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalOperationsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalName', models.CharField(max_length=30)),
                ('vetName', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
    ]
