# Generated by Django 4.0.5 on 2022-07-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_medication_surgicaloperations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='date',
            field=models.CharField(blank=True, default='2022-07-25', max_length=30, null=True),
        ),
    ]
