# Generated by Django 4.0.5 on 2022-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_locations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='service',
            field=models.CharField(choices=[('Wellness Exams & Vaccinations', 'Wellness Exams & Vaccinations'), ('Boarding & Grooming Services', 'Boarding & Grooming Services'), ('Animal Emergency Services', 'Animal Emergency Services')], default='Wellness Exams & Vaccinations', max_length=30),
            preserve_default=False,
        ),
    ]
