# Generated by Django 4.0.5 on 2022-07-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_medication_date_alter_messages_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviserequest',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('bending', 'bending'), ('dismissed', 'dismissed'), ('declined ', 'declined')], default='bending', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='surgicaloperationsrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('bending', 'bending'), ('dismissed', 'dismissed'), ('declined ', 'declined')], default='bending', max_length=30, null=True),
        ),
    ]
