# Generated by Django 4.0.5 on 2022-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_serviserequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviserequest',
            name='dismissUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviserequest',
            name='dismissVet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgicaloperationsrequest',
            name='dismissUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgicaloperationsrequest',
            name='dismissVet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviserequest',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('bending', 'bending'), ('declined ', 'declined')], default='bending', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='surgicaloperationsrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('bending', 'bending'), ('declined ', 'declined')], default='bending', max_length=30, null=True),
        ),
    ]
