# Generated by Django 4.0.5 on 2022-07-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_medication_adminstrationroute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgicaloperationsrequest',
            old_name='status',
            new_name='statusUser',
        ),
        migrations.RemoveField(
            model_name='surgicaloperationsrequest',
            name='dismissUser',
        ),
        migrations.RemoveField(
            model_name='surgicaloperationsrequest',
            name='dismissVet',
        ),
        migrations.AddField(
            model_name='surgicaloperationsrequest',
            name='statusVet',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('pending', 'pending'), ('declined ', 'declined')], default='pending', max_length=30, null=True),
        ),
    ]
