# Generated by Django 4.0.5 on 2022-07-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_status_surgicaloperationsrequest_statususer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicaloperationsrequest',
            name='statusUser',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='surgicaloperationsrequest',
            name='statusVet',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=30, null=True),
        ),
    ]
