# Generated by Django 4.0.5 on 2022-07-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_myuser_profile_pic_alter_vet_profile_pic'),
        ('api', '0037_rename_status_surgicaloperationsrequest_statususer_and_more'),
    ]

    operations = [
    ]
