# Generated by Django 4.0.5 on 2022-07-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_surgicaloperations_statususer_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='serviserequest',
            name='dismissUser',
        ),
        migrations.RemoveField(
            model_name='serviserequest',
            name='dismissVet',
        ),
        migrations.AddField(
            model_name='locations',
            name='owner',
            field=models.CharField(default='mostafamasrya', max_length=30),
        ),
        migrations.AddField(
            model_name='serviserequest',
            name='statusVet',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('pending', 'pending'), ('declined ', 'declined')], default='pending', max_length=30, null=True),
        ),
    ]
