# Generated by Django 4.0.5 on 2022-07-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_status_serviserequest_statususer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='owner',
            field=models.CharField(max_length=30),
        ),
    ]
