# Generated by Django 4.0.5 on 2022-07-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_locations_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviserequest',
            old_name='statusVet',
            new_name='statusOwner',
        ),
    ]
