# Generated by Django 4.0.5 on 2022-07-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_locations_website_link_and_more'),
        ('api', '0043_alter_medication_date_alter_messages_date_and_more'),
    ]

    operations = [
    ]
