# Generated by Django 4.0.5 on 2022-07-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_merge_20220728_0244'),
        ('api', '0044_merge_20220728_1039'),
    ]

    operations = [
    ]
