# Generated by Django 4.0.5 on 2022-07-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_merge_20220729_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicaloperations',
            name='message',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='medication',
            name='adminstrationRoute',
            field=models.CharField(blank=True, choices=[('Intramascular', 'Intramascular'), ('Intravenous', 'Intravenous'), ('Oral', 'Oral'), (
                'Sublingual', 'Sublingual'), ('Topical', 'Topical'), ('Ocular', 'Ocular'), ('Subcutaneous', 'Subcutaneous')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='date',
            field=models.CharField(
                blank=True, default='2022-07-29', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(default='2022-07-29', max_length=30),
        ),
        migrations.AlterField(
            model_name='surgicaloperations',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='surgicaloperations',
            name='operationName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='surgicaloperations',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
