# Generated by Django 4.0.5 on 2022-07-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_serviserequest_status_alter_medication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
