# Generated by Django 4.0.5 on 2022-08-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_serviserequest_status_locations_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[
                 ('service', 'service'), ('medication', 'medication'), ('surgery', 'surgery')], max_length=30)),
            ],
        ),
    ]
