# Generated by Django 4.1 on 2022-08-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_serviserequest_status_locations_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviserequest',
            name='status',
        ),
        migrations.AddField(
            model_name='locations',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviserequest',
            name='reasonUser',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='serviserequest',
            name='reasonVet',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='serviserequest',
            name='statusUser',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('pending', 'pending'), ('declined', 'declined')], default='accepted', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='surgicaloperations',
            name='reasonUser',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='surgicaloperations',
            name='reasonVet',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='medication',
            name='date',
            field=models.CharField(blank=True, default='2022-08-06', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(default='2022-08-06', max_length=30),
        ),
    ]
