# Generated by Django 4.0.5 on 2022-08-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_serviserequest_status_locations_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicaloperations',
            name='date',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='surgicaloperations',
            name='operationName',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='surgicaloperations',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surgicaloperations',
            name='reasonUser',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='surgicaloperations',
            name='reasonVet',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
